### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by sushma-4** [argonne-lcf/THAPI#5]
I have installed all the dependencies and was tying to `$make` after `configure` and encountered this:

```Making all in utils
make[1]: Entering directory '/home/demo/THAPI/utils'
make  all-am
make[2]: Entering directory '/home/demo/THAPI/utils'
make[2]: Leaving directory '/home/demo/THAPI/utils'
make[1]: Leaving directory '/home/demo/THAPI/utils'
Making all in opencl
make[1]: Entering directory '/home/demo/THAPI/opencl'
SRC_DIR=. ruby ./gen_opencl_probes.rb > opencl_tracepoints.tp
Traceback (most recent call last):
	4: from ./gen_opencl_probes.rb:1:in `<main>'
	3: from ./gen_opencl_probes.rb:1:in `require_relative'
	2: from /home/demo/THAPI/opencl/opencl_model.rb:1:in `<top (required)>'
	1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- nokogiri (LoadError)
make[1]: *** [Makefile:1635: opencl_tracepoints.tp] Error 1
make[1]: *** Deleting file 'opencl_tracepoints.tp'
make[1]: Leaving directory '/home/demo/THAPI/opencl'
make: *** [Makefile:404: all-recursive] Error 1
```

**Comment by sushma-4** [comment]
Thank you, seems like the issue is with `gem install` I was trying to get the missing dependencies, and keeps failing with 
```
ERROR:  While executing gem ... (Gem::Exception)
    OpenSSL is not available. Install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources
```

Tried everything to install and rebuild with ssl but still fails. I've raised an issue with Ruby as well. Waiting for their reply.

**Comment by sushma-4** [comment]
I just pulled and my configure still passes, make fails
